### PR TITLE
fixed:  Creating new project after eLabFTW eln import #78

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**

### CODE REVIEW

**Review by jmurugan-fzj — APPROVED** [review]

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj I cannot reproduce it because the video only shows the part after the error is there; the error being in the database. Since there is some database corruption: can you press ctrl-? (or Help->Verify database) and see what it is saying. 
Or keep the state and then put a breakpoint on file database.py line 600

Remember, to reset the database before starting: delete old and create a new (correct) project structure.

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj I cannot reproduce it because the video only shows the part after the error is there; the error being in the database. Since there is some database corruption: can you press ctrl-? (or Help->Verify database) and see what it is saying. Or keep the state and then put a breakpoint on file database.py line 600
> 
> Remember, to reset the database before starting: delete old and create a new (correct) project structure.

@SteffenBrinckmann Yes, it looks like the database has some shasum problems (shasum twice in view), could you see this video: [error_with_incosistent_db.webm](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu/download?path=%2FIssue76&files=error_with_incosistent_db.webm)

I have not deleted any project from the db so far, had only populated them using the repair setup, then imported the elabftw files and added some test projects via pasta GUI...

Additionally I have observed that when I switch to the elabftw project, I can see a very similar issue happening again which was reported earlier: _comment in project view #36_

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj repairing/resetting from the setup deletes everything in the process.
Can you try it again, sorry. We can also do it tomorrow together.

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj repairing/resetting from the setup deletes everything in the process. Can you try it again, sorry. We can also do it tomorrow together.

@SteffenBrinckmann I removed pasta fully along with the database and freshly installed the application with the sample project being generated by the setup/repair GUI module

After which I imported the elabftw projects, then also I could reproduce the same error, the shasum error is gone now but the database verification shows some different errors related to the imported elab projects, see the video please: [trials_after_couch_db_re_install.webm](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu/download?path=%2FIssue76&files=trials_after_couch_db_re_install.webm)

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj  I tried again, and cannot reproduce. We have to sit infront of the same computer, otherwise we go in loops.

**Review by jmurugan-fzj — APPROVED** [review]

**Pull request merged**
