### PR TITLE
docs(ontology): add help button functionality to ontology editor tool 

### PR DESCRIPTION
**Pull request by jmurugan-fzj**
- Added a new entry to the help page of PASTA-ELN for the Ontology Configuration tool
- Added user manual for the ontology editor tool and also embedded the respective document within the help page
- Corrected some spelling mistakes and other minor refactoring
- Corrected the failing tests and also pylint failure

### CODE REVIEW

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Please review "fix(ontology): save fails in ontology editor https://github.com/PASTA-ELN/pasta-eln/pull/50" and then "_fix(ontology): auto resizing the whole ontology editor window #51_" first and later have a look at this one, this branch is based on the others, once when you finalize the other PRs #50 & #51, I shall merge the previous ones and then the changes here will be more specific and shall be easier also for you to review...!

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj 
I did not encounter any bugs, so I will approve it. Great work. Just a few comments on changes in the layout that you might discuss when talking to HT:
- where can you reduce the text by using a clear icon (delete, move up?)
- I would suggest to hide the attachment section by default and only show it if the user wants to add those (makes only sense in instruments)
- Can you change the fontsize of "Edit Questionairies". Also not every word must be capitalized.

**Review by SteffenBrinckmann — APPROVED** [review]
See last comments. Also: not sure about the presentation, local

**Comment by SteffenBrinckmann** [comment]
Once you have that merged, I will release a new version based on that

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj I did not encounter any bugs, so I will approve it. Great work. Just a few comments on changes in the layout that you might discuss when talking to HT:
> 
> * where can you reduce the text by using a clear icon (delete, move up?)
> * I would suggest to hide the attachment section by default and only show it if the user wants to add those (makes only sense in instruments)
> * Can you change the fontsize of "Edit Questionairies". Also not every word must be capitalized.

@SteffenBrinckmann I have changed these comments also, please review again, if possible...Also for the fontsize, I tried to set the font for "Edit Questionnaires", but it looks like this is over ridden by the theme applied by PASTA app, similarly the "Capitalize" is also done by the parent theme!

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj  I don't understand, how can I see the changes. It is merged and hence closed.

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I meant about the changes made which you can see in the "Files changed" tab, if you have any feedback, you could still provide it there, but more important is the font size and general theme applied by the parent application which needs to be modified outside the the ontology editor component, we can discuss this in the future..

**Pull request merged**
