### PR TITLE
repaired #36 #20

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**

### CODE REVIEW

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann In my opinion, this looks a bit ugly with the text edit been introduced just alone for the comment in UI, why can't we simply wrap the text instead?

image

Also I have seen some errors been logged in the console while doing the comment edits

image

**Comment by jmurugan-fzj** [comment]
> The error messages are a bug and I repaired it.
> 
> Text area:
> 
> * ugliness: yes it is, also according to my view: I changed the colors to be better
> * the textarea has a big advantage: it renders markdown, which is the one format (along with plain text) for comments and contents. So to support markdown out of the box, we need the text area.
> 
> Now everything should be repaired.

@SteffenBrinckmann This looks much better now, but I seen a problem when I opened the project initially there were two comment sections, after the edit the issue got resolved

See the video here: [duplicate_comment_issue](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu#/files_mediaviewer/duplicate_comment_issue.webm)

Also I see a little bit of alignment problem with the others items in the project info, the old version was better aligned in my opinion
Screenshot from 2023-10-06 10-48-31

**Comment by SteffenBrinckmann** [comment]
Yes, it was a bug and I changed the alignment to be the same as the other items

**Review by jmurugan-fzj — APPROVED** [review]

**Comment by jmurugan-fzj** [comment]
> Yes, it was a bug and I changed the alignment to be the same as the other items

Yes this looks very good visually now, also the functionality works too..

**Pull request merged**
