### PR TITLE
Sb table bugs

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**
It repairs #113 and #114

### CODE REVIEW

**Comment by SteffenBrinckmann** [comment]
Can you first review PR #119 ? Then these checks should solve themselves?

**Comment by jmurugan-fzj** [comment]
> Can you first review PR #119 ? Then these checks should solve themselves?

@SteffenBrinckmann Do you mean the changes in #119 will fix the failing workflows?

**Comment by SteffenBrinckmann** [comment]
It repairs #113 and #114 only, the rest was a mistake in branch creation.

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj I merged the new main branch at it should be great

**Comment by SteffenBrinckmann** [comment]
found a connected bug: selection button appears if visibility is toggled in project view

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj it was indeed the same style of bug: forgot a 'self.'. Should be ready now

**Review by jmurugan-fzj — APPROVED** [review]

**Pull request merged**
