### PR TITLE
feat(ontology): auto-populating IRI fields of ontology editor tool

### PR DESCRIPTION
**Pull request by jmurugan-fzj**
- Added terminology_lookup_dialog.py with the base class auto generated by QTDesigner, along with terminology_lookup_service which retrieves the actual information from various portals saved as lookup services inside the terminology_lookup_config.json file. Also added LookupIRIAction which adds the button to the IRI line edits on both table view level and also on type level. LookupIRIAction contains the logic to show the lookup dialog, do the search and sets the accepted IRIs appopriately. Also added  iri_column_delegate.py for enabling the custom line-edits with the lookup action defined for the IRI column in the property table
- Modified ontology_configuration_extended.py to add lookup_iri_action whenever the label value is updated
- Added icons for the search portals png format within icons folder
- Adjusted and added tests for the changes done, Corrected the tests failures and also added more tests for better coverage
- Corrected and refactored the copyright statements and also the imports

### CODE REVIEW

**Comment by SteffenBrinckmann** [comment]
Can you please tell me how to get to the auto-populating IRI fields? I don't see the button for a dialog to open.

**Comment by jmurugan-fzj** [comment]
> Can you please tell me how to get to the auto-populating IRI fields? I don't see the button for a dialog to open.

@SteffenBrinckmann Could you see the orange right arrow buttons in the IRI line edits?

image

**Comment by SteffenBrinckmann** [comment]
Here you can see that I cannot see the buttons:
screenshot-5b8c1232

There is a button, which is invisible at the top (next to Projects) and that button works (though it is invisible) and the opening screen looks amazing.
There is no such button in the button rows.

**Comment by jmurugan-fzj** [comment]
> Here you can see that I cannot see the buttons: screenshot-5b8c1232
> 
> There is a button, which is invisible at the top (next to Projects) and that button works (though it is invisible) and the opening screen looks amazing. There is no such button in the button rows.

@SteffenBrinckmann Button will be displayed only in the edit mode of the IRI column in property table, can you try this way? Go to edit mode of IRI cell in property table to see an invisible button there?

**Comment by SteffenBrinckmann** [comment]
this might be a way to use the same icons throughout
```
  color = 'black' if widget is None else getColor(widget.comm.backend, 'primary')
  icon = qta.icon('fa.angle-right', color=color, scale_factor=1)
```

**Comment by jmurugan-fzj** [comment]
> qta.icon('fa.angle-right', color=color, scale_factor=1)

where is this qta package coming from? Do I have to install any additional package or did you mean qtawesome?

**Comment by SteffenBrinckmann** [comment]
The icon is now nice and shown and works.
But the icons in the table below are not shown, they are not present.

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj  sorry, I did not see the button in the table immediately: it appears after double click.

**Comment by SteffenBrinckmann** [comment]
I accept and you can decide if you want to implement the tweak mentioned in one of the comments.

**Review by SteffenBrinckmann — APPROVED** [review]

**Pull request merged**
