### PR TITLE
Bug if meta not in extractor

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**
create safeguard that prevents crashing

### CODE REVIEW

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj Can you understand why this is crashing? The fix is two lines in a code that is not even used in any tests, as far as I understand.

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj Can you understand why this is crashing? The fix is two lines in a code that is not even used in any tests, as far as I understand.

@SteffenBrinckmann Please do the following to make the test pass, 

In the file, [test_ontology_config_utility_functions.py](https://github.com/PASTA-ELN/pasta-eln/blob/78294a48f5b4c5a515ec519d64dbc016b31668d5/tests/app_tests/unit_tests/test_ontology_config_utility_functions.py)

Line number 79: Change `contents = {} ` to `contents = {"-version": 2}`

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj 
I added a timeout to all urlrequests and the default example uses a smaller wikipedia image
These things are related, since they all improve the installation of Pasta: hence one PR is appropriate

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Could you please make sure that the PR is associated with a github bug? I did not understand this bug clearly, specially the steps to reproduce it..!

**Review by jmurugan-fzj — APPROVED** [review]

**Pull request merged**
