### PR TITLE
Sb python3.12

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**

### CODE REVIEW

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj ready for review: mypy will fail until pyside6.7.... is released. There is a bug in that that causes mypy to fail. N

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj Can you understand these pytest issues, why is Save not part of the buttonbox anymore?
- the mypy test: I would ignore for now as it is a github-action / upstream issue. On my python 3.12 with that pyside version there is no issue.
- the comment in gui.py: I would leave in because it shows how the code should be, once the upstream bug is fixed. I also left the links so we easily can see if they are fixed. The main got a P2:Important priority. The current version is a work-around which works but is not ideal.

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj Can you understand these pytest issues, why is Save not part of the buttonbox anymore?
> 
> * the mypy test: I would ignore for now as it is a github-action / upstream issue (https://bugreports.qt.io/browse/PYSIDE-2696?attachmentViewMode=list and https://bugreports.qt.io/browse/PYSIDE-2665). On my python 3.12 with that pyside version there is no issue.
> * the comment in gui.py: I would leave in because it shows how the code should be, once the upstream bug is fixed. I also left the links so we easily can see if they are fixed. The main got a P2:Important priority. The current version is a work-around which works but is not ideal.

@SteffenBrinckmann Where do you see all these problems related to "Save" button? I see only a single error in the myPy action which is something related to indentation within base library file!
image

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj Sorry for being unclear: can you understand why PyTest&Coverage fails? There are some strange messages.

**Comment by SteffenBrinckmann** [comment]
There are also many warnings in pytest about fontawesome: repair those in this PR as well

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj Sorry for being unclear: can you understand why PyTest&Coverage fails? There are some strange messages.

@SteffenBrinckmann Corrected and committed the errors with 'PySide6.QtWidgets.QDialogButtonBox' already, there are a few other errors which needs further investigation! Need some more time..

image

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I changed python version to 3.10 except docbuild.yml (3.12) and installLinux.yml (3.12) since they fail otherwise. May be you had modified these actions to run for these versions alone!?

Pytest failures have been fixed and is running now, you can go ahead and fix the myPy issue!

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj OK, we have now found a system that is consistent: if all versions are 3.11 all tests run in successful (except the obvious mypy issue)
Same would be the case for python3.10, but 3.11 is more recent and hence let's stick with that.
*Lets stop working on this branch until the upstream people fix the mypy issue* THANKS for your help

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj The new version of pyside is out and it has the corrected grammar. Since we update from pyside 6.2... to 6.7... the types have become much more defined and consistent. As a result, I had to correct 200 mypy issues. The remaining mypy issues are from your code. How do we continue?

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj Yes, it it qt related and before the definitions of qt were not as well as they are now. For me 90% were true issues.

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Okay, I am working presently on feature/10-show-completed-module, as soon as I finalize this, I can work on this, is this fine? If so, could you please move it back to draft, as soon as I begin, I shall move it back!

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj Yes, it it qt related and before the definitions of qt were not as well as they are now. For me 90% were true issues.

@SteffenBrinckmann I see an error been thrown when setting up the .venv for PASTA and this is related to the python version (Python 3.10.12) which I have in my system presently, I think, I have to upgrade the python version also to the same which you have in your system..

I do not want to upgrade the python version manually (which could possibly mess my present setup: [link](https://www.reddit.com/r/Ubuntu/comments/18xzoic/python_version_upgrade/)), instead I will go an official upgrade of Ubuntu (my version: 22.04.1-Ubuntu) to the same version as you have. Could you please provide the version information (both ubuntu & python), so that I can ask Ramdan to do an upgrade for me?

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj Yes, it it qt related and before the definitions of qt were not as well as they are now. For me 90% were true issues.

@SteffenBrinckmann I see some error with the .venv setup for the pasta project and this is because of the old version (Python 3.10.12) of python in my system.
image

I would like to upgrade the Ubuntu (22.04.1-Ubuntu) also to the same version as you have which might also bring the latest version of python. Could you please provide the version of ubuntu & python you have, so that I can ask Ramadan to upgrade it soon too?

Do not want to upgrade the python manually, since there are chances that this could mess up my existing setup: [link](https://www.reddit.com/r/Ubuntu/comments/18xzoic/python_version_upgrade/)

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj I use Ubuntu 24.04 and python 3.12

**Comment by SteffenBrinckmann** [comment]
As you can see from the many mypy commits, my system did not give the same errors as the GitHub action. The GitHub action is the measure, and I repaired, committed, checked again until there was success

**Review by jmurugan-fzj — APPROVED** [review]

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I had corrected the myPy errors along with the tests, quickly tested the corrected features too and they seem to be working fine, if you are confident about the other features in PASTA, please go ahead and do the merge, but in any-case, I think it's always better to do a whole feature test with the latest versions of the dependencies!

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Would you like to merge this PR or want to wait a bit more? I am thinking to make changes on a new branch (for #301) based on this one, because my setup is also upgraded to the new python version and so on... If you have a different thought, please let me know, I shall wait until this PR is finalized..

**Pull request merged**
