### PR TITLE
Repair bugs in import of data from .eln file

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**
Also:
- created test cases that should work on all computers but not on github actions
  - "pytest -s --no-skip tests/"
- added a space in setup-dialog (does not warrant a separate PR)

Repaired issues #37 and #38

### CODE REVIEW

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I tried to check this issue by following the below steps:

- Checked the latest version from [github](https://github.com/PASTA-ELN/pasta-eln/tree/sb_bugs_exportImport) 
- Run the pasta app
- Clicked on import menu item and immediately I see the following error, Can you check why this is occurring?
- image

**Comment by SteffenBrinckmann** [comment]
It seems you selected 'cancel', i.e. not a file, and then the software crashed. Implemented a check that only if a file is selected, import will initiate.

**Comment by jmurugan-fzj** [comment]
> It seems you selected 'cancel', i.e. not a file, and then the software crashed. Implemented a check that only if a file is selected, import will initiate.

@SteffenBrinckmann I did not understand actually, I have not done anything except the steps mentioned in my previous comment, fresh installation of pasta app and as the first step, I clicked on "Import .eln" menu item
image

**Comment by SteffenBrinckmann** [comment]
I really don't understand how that can happen as there is a code-line that opens the dialog to open the file. When I try it, the dialog opens and it works as expected. 
With the debugger, can you set a breakpoint at gui.py:147 "fileName = QFileDialog.getOpenFileName"
and then run it and see if it goes through those steps?

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I verified the import and it works as expected, could you merge from the main branch and commit, because I see the changes from the previous PR also here, would be easy for me to review the changes then!

**Comment by SteffenBrinckmann** [comment]
I did that.

**Review by jmurugan-fzj — APPROVED** [review]

**Pull request merged**
