### PR TITLE
ci(ontology): added pytest and coverage calculation as a workflow

### PR DESCRIPTION
**Pull request by jmurugan-fzj**
- Added the workflow for the pytest and coverage calculation
- Disabled the tests until proper mocking of back-end data  is enabled: test_99_3Projects.py, test_01_demoIndentation.py, test_02_demoIndentation_ExportImport.py & test_pasta_app_ui.py

### CODE REVIEW

**Comment by SteffenBrinckmann** [comment]
This is something that requires discussion in a meeting on Thursday:
- for me -- with the data -- the tests are running and are worthwhile since they allow testing.
- for you -- without the data -- the tests are unsuccessful
The issues:
- the data is not secret, however it is so large that we fast fill up the github quota
- the testing for that data has a larger number of requirements, which we would have to add to the devel

**Comment by SteffenBrinckmann** [comment]
I changed my mind. Let's do this. I will adopt my test-scripts and in the future we can find a solution to store the data and the extractors remotely and test it from there.

**Comment by SteffenBrinckmann** [comment]
Please also note: the requirements*.txt are autogenerated from the create-a-release-script for pypi. I have to change that.

**Review by SteffenBrinckmann — APPROVED** [review]

**Review by SteffenBrinckmann — APPROVED** [review]

**Comment by jmurugan-fzj** [comment]
> Please also note: the requirements*.txt are autogenerated from the create-a-release-script for pypi. I have to change that.

@SteffenBrinckmann Yes, I have seen that, I re-generated the scripts from setup.cfg by executing releaseVersion.py file.. hope this is the same approach which you do too..

**Comment by jmurugan-fzj** [comment]
> I changed my mind. Let's do this. I will adopt my test-scripts and in the future we can find a solution to store the data and the extractors remotely and test it from there.

@SteffenBrinckmann Yes that would be the right way, anyway if you think these tests are really on integration level, then we might need to also think about the availability of database and all inside the github action container. Since we do not have any integration setup or CI pipeline, easy way might be to mock the DB. In my opinion tests should never modify the local database contents when run locally, that's what I observed that the local database is populated with the test data and also overwrite the existing research Db, either they should have a mocked database or an individual integration setup with the database on its own to run the tests..

**Pull request merged**
